#!/usr/bin/env bash
cd `dirname $0`

svn co https://svn.felspar.com/external/Boost
Boost/install `lsb_release -cs`
svn co https://svn.felspar.com/external/OpenSSL

svn co https://svn.felspar.com/public/fost-base/trunk/fost-base
svn co https://svn.felspar.com/public/fost-internet/trunk/fost-internet
svn co https://svn.felspar.com/public/fost-orm/trunk/fost-orm

kirit-com/compile $*

